// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AudioPacketMessage {
    #[prost(bytes = "vec", tag = "1")]
    pub buffer: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub sample_rate: u32,
    #[prost(uint32, tag = "3")]
    pub channel_count: u32,
    #[prost(uint32, tag = "4")]
    pub audio_format: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AudioPacketMessageOrdered {
    #[prost(uint32, tag = "1")]
    pub sequence_number: u32,
    #[prost(message, optional, tag = "2")]
    pub audio_packet: ::core::option::Option<AudioPacketMessage>,
}
