// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AudioPacketMessage {
    #[prost(bytes = "vec", tag = "1")]
    pub buffer: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub sample_rate: u32,
    #[prost(uint32, tag = "3")]
    pub channel_count: u32,
    #[prost(uint32, tag = "4")]
    pub audio_format: u32,
}
