//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidMic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainWindow_AudioDisplayEnabled {
            get {
                return ((bool)(this["MainWindow_AudioDisplayEnabled"]));
            }
            set {
                this["MainWindow_AudioDisplayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainWindow_AudioDeviceIdx {
            get {
                return ((int)(this["MainWindow_AudioDeviceIdx"]));
            }
            set {
                this["MainWindow_AudioDeviceIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float MainWindow_AudioVolume {
            get {
                return ((float)(this["MainWindow_AudioVolume"]));
            }
            set {
                this["MainWindow_AudioVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainWindow_ConnectViaBluetooth {
            get {
                return ((bool)(this["MainWindow_ConnectViaBluetooth"]));
            }
            set {
                this["MainWindow_ConnectViaBluetooth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float AdvancedWindow_PitchShifterVal {
            get {
                return ((float)(this["AdvancedWindow_PitchShifterVal"]));
            }
            set {
                this["AdvancedWindow_PitchShifterVal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedWindow_PitchShifterEnabled {
            get {
                return ((bool)(this["AdvancedWindow_PitchShifterEnabled"]));
            }
            set {
                this["AdvancedWindow_PitchShifterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AdvancedWindow_WhiteNoiseVal {
            get {
                return ((float)(this["AdvancedWindow_WhiteNoiseVal"]));
            }
            set {
                this["AdvancedWindow_WhiteNoiseVal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedWindow_WhiteNoiseEnabled {
            get {
                return ((bool)(this["AdvancedWindow_WhiteNoiseEnabled"]));
            }
            set {
                this["AdvancedWindow_WhiteNoiseEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AdvancedWindow_RepeatTrackStrength {
            get {
                return ((float)(this["AdvancedWindow_RepeatTrackStrength"]));
            }
            set {
                this["AdvancedWindow_RepeatTrackStrength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float AdvancedWindow_RepeatTrackLoop {
            get {
                return ((float)(this["AdvancedWindow_RepeatTrackLoop"]));
            }
            set {
                this["AdvancedWindow_RepeatTrackLoop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedWindow_RepeatTrackEnabled {
            get {
                return ((bool)(this["AdvancedWindow_RepeatTrackEnabled"]));
            }
            set {
                this["AdvancedWindow_RepeatTrackEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedWindow_SpeexDenoise {
            get {
                return ((bool)(this["AdvancedWindow_SpeexDenoise"]));
            }
            set {
                this["AdvancedWindow_SpeexDenoise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedWindow_SpeexAGC {
            get {
                return ((bool)(this["AdvancedWindow_SpeexAGC"]));
            }
            set {
                this["AdvancedWindow_SpeexAGC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedWindow_SpeexVAD {
            get {
                return ((bool)(this["AdvancedWindow_SpeexVAD"]));
            }
            set {
                this["AdvancedWindow_SpeexVAD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedWindow_SpeexEcho {
            get {
                return ((bool)(this["AdvancedWindow_SpeexEcho"]));
            }
            set {
                this["AdvancedWindow_SpeexEcho"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectNetworkWindow_Idx {
            get {
                return ((int)(this["SelectNetworkWindow_Idx"]));
            }
            set {
                this["SelectNetworkWindow_Idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int MainWindow_PlayerDesiredLatency {
            get {
                return ((int)(this["MainWindow_PlayerDesiredLatency"]));
            }
            set {
                this["MainWindow_PlayerDesiredLatency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainWindow_ConnectViaWifi {
            get {
                return ((bool)(this["MainWindow_ConnectViaWifi"]));
            }
            set {
                this["MainWindow_ConnectViaWifi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainWindow_ConnectViaUsb {
            get {
                return ((bool)(this["MainWindow_ConnectViaUsb"]));
            }
            set {
                this["MainWindow_ConnectViaUsb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedWindow_Rnnoise {
            get {
                return ((bool)(this["AdvancedWindow_Rnnoise"]));
            }
            set {
                this["AdvancedWindow_Rnnoise"] = value;
            }
        }
    }
}
