name: Create Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-all:
    name: Build All Platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: macos
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies (Linux)
        if: matrix.platform == 'linux'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libjack-jackd2-dev libxkbcommon-dev protobuf-compiler

      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows'
        run: choco install protoc

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos'
        run: brew install protobuf

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./RustApp -> target"
          
      - name: Install cargo-packager
        if: matrix.platform == 'windows' || matrix.platform == 'macos'
        run: cargo install cargo-packager
        
      - name: Build (Linux)
        if: matrix.platform == 'linux'
        working-directory: ./RustApp
        run: cargo build --release
        
      - name: Package (Windows/macOS)
        if: matrix.platform == 'windows' || matrix.platform == 'macos'
        working-directory: ./RustApp
        run: |
          # Debug what cargo-packager is doing
          echo "Running cargo packager with verbose output"
          cargo packager --release -v
        
      - name: Debug output directory structure
        shell: bash
        run: |
          echo "Listing target directory structure"
          find ./RustApp/target -type f -not -path "*/deps/*" -not -path "*/examples/*" -not -path "*/incremental/*" | sort
          
      # For Linux
      - name: Upload Linux binary
        if: matrix.platform == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: androidmic-linux
          path: ./RustApp/target/release/android-mic
          if-no-files-found: warn
          
      # For Windows
      - name: Upload Windows built files
        if: matrix.platform == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: androidmic-windows
          path: |
            ./RustApp/target/release/android-mic.exe
            ./RustApp/target/release/bundles/**/*
          if-no-files-found: warn
          
      # For macOS
      - name: Upload macOS built files
        if: matrix.platform == 'macos'
        uses: actions/upload-artifact@v4
        with:
          name: androidmic-macos
          path: |
            ./RustApp/target/release/android-mic
            ./RustApp/target/release/bundles/**/*
          if-no-files-found: warn

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: ./Android
        run: chmod +x gradlew

      - name: Build Release APK
        working-directory: ./Android
        run: ./gradlew assembleRelease
        
      - name: List APK files
        working-directory: ./Android
        run: find app/build/outputs -name "*.apk"
        
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: androidmic-android-apk
          path: ./Android/app/build/outputs/apk/release/*.apk
          if-no-files-found: warn

  create-release:
    name: Create GitHub Release
    needs: [build-all, build-android]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: all-artifacts
          
      - name: Display structure of downloaded files
        run: find all-artifacts -type f | sort
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: all-artifacts/**/*
          body: |
            ## AndroidMic ${{ github.ref_name }}
            
            ### What's Changed
            <!-- You can add manual notes here, they will be combined with automated notes -->
             - Several improvements and bug fixed
            
            ### Installation
            - For Android: Install the `.apk` file
            - For Linux: Install the `android-mic` binary
            - For Windows: Download and run the `.exe`